import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';

// Define local fonts
const bagoss = localFont({
  src: '../public/fonts/Bagoss/BagossTRIAL-VF.ttf',
  variable: '--font-bagos',
  display: 'swap',
});

const font01 = localFont({
  src: '../public/fonts/Font-01/177dfc527bd44fad48eb07c66fb3cc41.woff2',
  variable: '--font-font-01',
  display: 'swap',
});

const font02 = localFont({
  src: '../public/fonts/Font-02/e72bba62e4760c045a231a26738e7a41.woff2',
  variable: '--font-font-02',
  display: 'swap',
});

const graphik01 = localFont({
  src: '../public/fonts/Graphik/177dfc527bd44fad48eb07c66fb3cc41.woff2',
  variable: '--font-graphik-01',
  display: 'swap',
});

const graphik02 = localFont({
  src: '../public/fonts/Graphik/e72bba62e4760c045a231a26738e7a41.woff2',
  variable: '--font-graphik-02',
  display: 'swap',
});

const graphikMedium = localFont({
  src: '../public/fonts/Graphik/Graphik-Medium.woff2',
  variable: '--font-graphik-medium',
  display: 'swap',
});

const ppAgrandir = localFont({
  src: [
    {
      path: '../public/fonts/PP-Agrandir/PPAgrandir-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/PP-Agrandir/PPAgrandir-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-pp-agrandir',
});

const sohne = localFont({
  src: [
    {
      path: '../public/fonts/Sohne/Sohne-Buch.otf',
      weight: '500',
      style: 'normal',
    }
  ],
  variable: '--font-sohne',
});

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${bagoss.variable} ${font01.variable} ${font02.variable} ${graphik01.variable} ${graphik02.variable} ${graphikMedium.variable} ${ppAgrandir.variable} ${sohne.variable}`}>
      <body>{children}</body>
    </html>
  );
}